# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 'Do Not Reply'
email: tom@dp.la
description: > # this means to ignore newlines until "baseurl:"
  no-reply
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://no-reply.github.io" # the base hostname & protocol for your site
twitter_username: no_reply
github_username:  no-reply

# Build settings
markdown: kramdown
highlighter: rouge

# Collections
# @see http://jekyllrb.com/docs/collections/
collections:
  notes:
    output: true



